server:
  port: 0
spring:
  application:
    name: userService
  ## MongoDB Properties
  data:
    mongodb:
      uri: mongodb+srv://abhaytechhub:abhaytechhub@cluster0.yky0qyx.mongodb.net/jobify?retryWrites=true&w=majority&appName=Cluster0
  ## Zipkin and Sleuth Properties
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

## Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# JWT properties
jwt:
  secret:
    key: secret_secret_secret_secret_secret_secret_secret_secret_secret_secret